version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs
hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/before-install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: /home/ubuntu/scripts/after-install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/scripts/boot.sh
      timeout: 180
      runas: root
